% AMS figure widths, given in picas, converted to points (1 pica=12 points)
figure_width_1col = 19*12*scaleFactor;
figure_width_medium = 27*12*scaleFactor;
figure_width_large = 33*12*scaleFactor;
figure_width_2col = 39*12*scaleFactor;
figure_font = 'Helvetica';
figure_legend_size = 9*scaleFactor;
figure_axis_tick_size = 8*scaleFactor;
figure_axis_label_size = 10*scaleFactor;
figure_title_size = 11*scaleFactor;