remote_theme: just-the-docs/just-the-docs
plugins: - jekyll-remote-theme # add this line to the plugins list if you already have one
title: WaveVortexModel
description: A decompose a rotating stratified fluid into waves and vortices
